# PROGRAM DO WYSYŁANIA I ODBIERANIA MAILI
# PAWEŁ PUŹNIAK 2019
# UNIWERSYTET PEDAGOGICZNY IM. KEN W KRAKOWIE
# PROJEKT ZALICZENIOWY JĘZYKI SKRYPTOWE

# --- MENU STEROWANIA POCZĄTEK ---

# --- MENU STEROWANIA KONIEC ---



# --- FUNKCJA WYSYŁKI JEDNEGO MAILA POCZĄTEK ---

# --- FUNKCJA WYSYŁKI JEDNEGO MAILA KONIEC ---



# --- FUNKCJA WYSYŁKI WIELU MAILI POCZĄTEK ---

# --- FUNKCJA WYSYŁKI WIELU MAILI KONIEC ---



# --- FUNKCJA ODBIORU MAILI POCZĄTEK ---

# --- FUNKCJA ODBIORU MAILI KONIEC ---



# --- KONIEC PROGRAMU ---

koniec = input()
if koniec == True:
    sys.exit()